-- migrate:up

-- ==========================================
-- Grip catalog: inserts and thumb hardware (platform data)
-- ==========================================
-- Manufacturer lines (VISE, Turbo, JoPo) and their sizes, each with the O.D.
-- it's drilled for. Maintained by us, shared by every company, read-only to
-- the API. The rows below are generated by db/seed/grip_catalog.py.

create table grip_line (
    id           uuid primary key default gen_random_uuid(),
    manufacturer text not null check (manufacturer in ('VISE', 'TURBO', 'JOPO')),
    name         text not null,
    kind         text not null check (kind in ('FINGER_INSERT', 'FINGER_SLUG', 'THUMB_INSERT', 'THUMB_SLUG', 'INTERCHANGEABLE_THUMB')),
    colors       text[] not null default '{}',     -- chosen on the work order
    active       boolean not null default true,
    unique (manufacturer, name)
);

create table grip_size (
    id           uuid primary key default gen_random_uuid(),
    line_id      uuid not null references grip_line(id),
    size64       smallint not null check (size64 > 0),     -- grip size (finger/thumb hole), or slug size
    label        text not null,                            -- the manufacturer's label: '8.5', '61', '1/6', '13/16'
    od64_choices smallint[] not null check (cardinality(od64_choices) >= 1),  -- O.D. bit(s); the first is the default
    collar       boolean not null default false,           -- drilled with a preset-collar hardware bit
    unique (line_id, size64)
);

grant select on grip_line, grip_size to drilld_app;

-- ==========================================
-- What each location carries (tenant data): line and size, no color
-- ==========================================

create table location_grip_stock (
    company_id   uuid not null,
    location_id  uuid not null,
    grip_size_id uuid not null references grip_size(id),
    created_at   timestamptz not null default now(),
    primary key (location_id, grip_size_id),
    foreign key (company_id, location_id) references location(company_id, id) on delete cascade
);

grant select, insert, delete on location_grip_stock to drilld_app;
alter table location_grip_stock enable row level security;
create policy tenant_isolation on location_grip_stock
    using (company_id = app_company_id())
    with check (company_id = app_company_id());

-- ==========================================
-- Catalog rows
-- ==========================================

insert into grip_line (manufacturer, name, kind, colors) values ('VISE', 'P/O Power Lift & Oval', 'FINGER_INSERT', array['Yellow', 'White', 'Black', 'Clear', 'Neon', 'Green', 'Orange', 'Blue', 'Purple', 'Pink', 'Red', 'Grape']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (36, '0', array[62]::smallint[], false),
    (37, '0.5', array[62]::smallint[], false),
    (38, '1', array[62]::smallint[], false),
    (39, '1.5', array[62]::smallint[], false),
    (40, '2', array[62]::smallint[], false),
    (41, '2.5', array[62]::smallint[], false),
    (42, '3', array[62]::smallint[], false),
    (43, '3.5', array[62]::smallint[], false),
    (44, '4', array[62]::smallint[], false),
    (45, '4.5', array[62]::smallint[], false),
    (46, '5', array[62]::smallint[], false),
    (47, '5.5', array[62]::smallint[], false),
    (48, '6', array[62]::smallint[], false),
    (49, '6.5', array[62]::smallint[], false),
    (50, '7', array[62]::smallint[], false),
    (51, '7.5', array[62]::smallint[], false),
    (52, '8', array[62]::smallint[], false),
    (53, '8.5', array[66]::smallint[], false),
    (54, '9', array[66]::smallint[], false),
    (55, '9.5', array[66]::smallint[], false),
    (56, '10', array[66]::smallint[], false),
    (57, '10.5', array[66]::smallint[], false),
    (58, '11', array[66]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'VISE' and l.name = 'P/O Power Lift & Oval';

insert into grip_line (manufacturer, name, kind, colors) values ('VISE', 'P/S Power Lift & Semi', 'FINGER_INSERT', array['Yellow', 'White', 'Black', 'Clear', 'Neon', 'Green', 'Orange', 'Blue', 'Purple', 'Pink', 'Red']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (36, '0', array[62]::smallint[], false),
    (37, '0.5', array[62]::smallint[], false),
    (38, '1', array[62]::smallint[], false),
    (39, '1.5', array[62]::smallint[], false),
    (40, '2', array[62]::smallint[], false),
    (41, '2.5', array[62]::smallint[], false),
    (42, '3', array[62]::smallint[], false),
    (43, '3.5', array[62]::smallint[], false),
    (44, '4', array[62]::smallint[], false),
    (45, '4.5', array[62]::smallint[], false),
    (46, '5', array[62]::smallint[], false),
    (47, '5.5', array[62]::smallint[], false),
    (48, '6', array[62]::smallint[], false),
    (49, '6.5', array[62]::smallint[], false),
    (50, '7', array[62]::smallint[], false),
    (51, '7.5', array[62]::smallint[], false),
    (52, '8', array[62]::smallint[], false),
    (53, '8.5', array[66]::smallint[], false),
    (54, '9', array[66]::smallint[], false),
    (55, '9.5', array[66]::smallint[], false),
    (56, '10', array[66]::smallint[], false),
    (57, '10.5', array[66]::smallint[], false),
    (58, '11', array[66]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'VISE' and l.name = 'P/S Power Lift & Semi';

insert into grip_line (manufacturer, name, kind, colors) values ('VISE', 'O/PO Oval & Power Lift Oval', 'FINGER_INSERT', array['Yellow', 'White', 'Black', 'Clear', 'Neon', 'Green', 'Orange', 'Blue', 'Purple', 'Pink', 'Red']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (36, '0', array[62]::smallint[], false),
    (37, '0.5', array[62]::smallint[], false),
    (38, '1', array[62]::smallint[], false),
    (39, '1.5', array[62]::smallint[], false),
    (40, '2', array[62]::smallint[], false),
    (41, '2.5', array[62]::smallint[], false),
    (42, '3', array[62]::smallint[], false),
    (43, '3.5', array[62]::smallint[], false),
    (44, '4', array[62]::smallint[], false),
    (45, '4.5', array[62]::smallint[], false),
    (46, '5', array[62]::smallint[], false),
    (47, '5.5', array[62]::smallint[], false),
    (48, '6', array[62]::smallint[], false),
    (49, '6.5', array[62]::smallint[], false),
    (50, '7', array[62]::smallint[], false),
    (51, '7.5', array[62]::smallint[], false),
    (52, '8', array[62]::smallint[], false),
    (53, '8.5', array[66]::smallint[], false),
    (54, '9', array[66]::smallint[], false),
    (55, '9.5', array[66]::smallint[], false),
    (56, '10', array[66]::smallint[], false),
    (57, '10.5', array[66]::smallint[], false),
    (58, '11', array[66]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'VISE' and l.name = 'O/PO Oval & Power Lift Oval';

insert into grip_line (manufacturer, name, kind, colors) values ('VISE', 'P/O 7/8″ O.D.', 'FINGER_INSERT', array['Yellow', 'White', 'Black', 'Green', 'Orange', 'Blue', 'Purple', 'Pink', 'Red']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (34, '-1', array[56]::smallint[], false),
    (36, '0', array[56]::smallint[], false),
    (38, '1', array[56]::smallint[], false),
    (40, '2', array[56]::smallint[], false),
    (42, '3', array[56]::smallint[], false),
    (44, '4', array[56]::smallint[], false),
    (46, '5', array[56]::smallint[], false),
    (48, '6', array[56]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'VISE' and l.name = 'P/O 7/8″ O.D.';

insert into grip_line (manufacturer, name, kind, colors) values ('VISE', 'P/S 7/8″ O.D.', 'FINGER_INSERT', array['Yellow', 'White', 'Black', 'Clear', 'Green', 'Orange', 'Pink']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (34, '-1', array[56]::smallint[], false),
    (35, '-0.5', array[56]::smallint[], false),
    (36, '0', array[56]::smallint[], false),
    (37, '0.5', array[56]::smallint[], false),
    (38, '1', array[56]::smallint[], false),
    (39, '1.5', array[56]::smallint[], false),
    (40, '2', array[56]::smallint[], false),
    (41, '2.5', array[56]::smallint[], false),
    (42, '3', array[56]::smallint[], false),
    (43, '3.5', array[56]::smallint[], false),
    (44, '4', array[56]::smallint[], false),
    (45, '4.5', array[56]::smallint[], false),
    (46, '5', array[56]::smallint[], false),
    (47, '5.5', array[56]::smallint[], false),
    (48, '6', array[56]::smallint[], false),
    (49, '6.5', array[56]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'VISE' and l.name = 'P/S 7/8″ O.D.';

insert into grip_line (manufacturer, name, kind, colors) values ('VISE', 'O/PO 7/8″ O.D.', 'FINGER_INSERT', array['Yellow', 'White', 'Black', 'Clear', 'Green', 'Orange', 'Pink']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (34, '-1', array[56]::smallint[], false),
    (35, '-0.5', array[56]::smallint[], false),
    (36, '0', array[56]::smallint[], false),
    (37, '0.5', array[56]::smallint[], false),
    (38, '1', array[56]::smallint[], false),
    (39, '1.5', array[56]::smallint[], false),
    (40, '2', array[56]::smallint[], false),
    (41, '2.5', array[56]::smallint[], false),
    (42, '3', array[56]::smallint[], false),
    (43, '3.5', array[56]::smallint[], false),
    (44, '4', array[56]::smallint[], false),
    (45, '4.5', array[56]::smallint[], false),
    (46, '5', array[56]::smallint[], false),
    (47, '5.5', array[56]::smallint[], false),
    (48, '6', array[56]::smallint[], false),
    (49, '6.5', array[56]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'VISE' and l.name = 'O/PO 7/8″ O.D.';

insert into grip_line (manufacturer, name, kind, colors) values ('VISE', 'Vinyl Oval with Nubs', 'FINGER_INSERT', array['Grape']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (37, '0.5', array[62]::smallint[], false),
    (38, '1', array[62]::smallint[], false),
    (39, '1.5', array[62]::smallint[], false),
    (40, '2', array[62]::smallint[], false),
    (41, '2.5', array[62]::smallint[], false),
    (42, '3', array[62]::smallint[], false),
    (43, '3.5', array[62]::smallint[], false),
    (44, '4', array[62]::smallint[], false),
    (45, '4.5', array[62]::smallint[], false),
    (46, '5', array[62]::smallint[], false),
    (47, '5.5', array[62]::smallint[], false),
    (48, '6', array[62]::smallint[], false),
    (49, '6.5', array[62]::smallint[], false),
    (50, '7', array[62]::smallint[], false),
    (51, '7.5', array[62]::smallint[], false),
    (52, '8', array[62]::smallint[], false),
    (53, '8.5', array[66]::smallint[], false),
    (54, '9', array[66]::smallint[], false),
    (55, '9.5', array[66]::smallint[], false),
    (56, '10', array[66]::smallint[], false),
    (57, '10.5', array[66]::smallint[], false),
    (58, '11', array[66]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'VISE' and l.name = 'Vinyl Oval with Nubs';

insert into grip_line (manufacturer, name, kind, colors) values ('VISE', 'Blue Silicone Round with Nubs', 'FINGER_INSERT', array['Blue']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (36, '0', array[62]::smallint[], false),
    (38, '1', array[62]::smallint[], false),
    (40, '2', array[62]::smallint[], false),
    (42, '3', array[62]::smallint[], false),
    (44, '4', array[62]::smallint[], false),
    (46, '5', array[62]::smallint[], false),
    (48, '6', array[62]::smallint[], false),
    (50, '7', array[62]::smallint[], false),
    (52, '8', array[62]::smallint[], false),
    (54, '9', array[66]::smallint[], false),
    (56, '10', array[66]::smallint[], false),
    (58, '11', array[66]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'VISE' and l.name = 'Blue Silicone Round with Nubs';

insert into grip_line (manufacturer, name, kind, colors) values ('VISE', 'Blue Silicone Oval with Nubs', 'FINGER_INSERT', array['Blue']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (36, '0', array[62]::smallint[], false),
    (38, '1', array[62]::smallint[], false),
    (40, '2', array[62]::smallint[], false),
    (42, '3', array[62]::smallint[], false),
    (44, '4', array[62]::smallint[], false),
    (46, '5', array[62]::smallint[], false),
    (48, '6', array[62]::smallint[], false),
    (50, '7', array[62]::smallint[], false),
    (52, '8', array[62]::smallint[], false),
    (54, '9', array[66]::smallint[], false),
    (56, '10', array[66]::smallint[], false),
    (58, '11', array[66]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'VISE' and l.name = 'Blue Silicone Oval with Nubs';

insert into grip_line (manufacturer, name, kind, colors) values ('VISE', 'Blue Silicone Power Lift', 'FINGER_INSERT', array['Blue']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (36, '0', array[62]::smallint[], false),
    (38, '1', array[62]::smallint[], false),
    (40, '2', array[62]::smallint[], false),
    (42, '3', array[62]::smallint[], false),
    (44, '4', array[62]::smallint[], false),
    (46, '5', array[62]::smallint[], false),
    (48, '6', array[62]::smallint[], false),
    (50, '7', array[62]::smallint[], false),
    (52, '8', array[62]::smallint[], false),
    (54, '9', array[66]::smallint[], false),
    (56, '10', array[66]::smallint[], false),
    (58, '11', array[66]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'VISE' and l.name = 'Blue Silicone Power Lift';

insert into grip_line (manufacturer, name, kind, colors) values ('VISE', 'Blue Silicone Smooth Oval', 'FINGER_INSERT', array['Blue']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (36, '0', array[62]::smallint[], false),
    (38, '1', array[62]::smallint[], false),
    (40, '2', array[62]::smallint[], false),
    (42, '3', array[62]::smallint[], false),
    (44, '4', array[62]::smallint[], false),
    (46, '5', array[62]::smallint[], false),
    (48, '6', array[62]::smallint[], false),
    (50, '7', array[62]::smallint[], false),
    (52, '8', array[62]::smallint[], false),
    (54, '9', array[66]::smallint[], false),
    (56, '10', array[66]::smallint[], false),
    (58, '11', array[66]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'VISE' and l.name = 'Blue Silicone Smooth Oval';

insert into grip_line (manufacturer, name, kind, colors) values ('VISE', 'Blue Silicone Semi Grip', 'FINGER_INSERT', array['Blue']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (36, '0', array[62]::smallint[], false),
    (38, '1', array[62]::smallint[], false),
    (40, '2', array[62]::smallint[], false),
    (42, '3', array[62]::smallint[], false),
    (44, '4', array[62]::smallint[], false),
    (46, '5', array[62]::smallint[], false),
    (48, '6', array[62]::smallint[], false),
    (50, '7', array[62]::smallint[], false),
    (52, '8', array[62]::smallint[], false),
    (54, '9', array[66]::smallint[], false),
    (56, '10', array[66]::smallint[], false),
    (58, '11', array[66]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'VISE' and l.name = 'Blue Silicone Semi Grip';

insert into grip_line (manufacturer, name, kind, colors) values ('VISE', 'IF Interchangeable Finger Oval', 'FINGER_INSERT', '{}'::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (40, '2', array[64, 65, 66]::smallint[], false),
    (41, '2.5', array[64, 65, 66]::smallint[], false),
    (42, '3', array[64, 65, 66]::smallint[], false),
    (43, '3.5', array[64, 65, 66]::smallint[], false),
    (44, '4', array[64, 65, 66]::smallint[], false),
    (45, '4.5', array[64, 65, 66]::smallint[], false),
    (46, '5', array[64, 65, 66]::smallint[], false),
    (47, '5.5', array[64, 65, 66]::smallint[], false),
    (48, '6', array[64, 65, 66]::smallint[], false),
    (49, '6.5', array[64, 65, 66]::smallint[], false),
    (50, '7', array[64, 65, 66]::smallint[], false),
    (51, '7.5', array[64, 65, 66]::smallint[], false),
    (52, '8', array[64, 65, 66]::smallint[], false),
    (53, '8.5', array[64, 65, 66]::smallint[], false),
    (54, '9', array[64, 65, 66]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'VISE' and l.name = 'IF Interchangeable Finger Oval';

insert into grip_line (manufacturer, name, kind, colors) values ('VISE', 'IF Interchangeable Finger Round', 'FINGER_INSERT', array['Black']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (40, '2', array[64, 65, 66]::smallint[], false),
    (41, '2.5', array[64, 65, 66]::smallint[], false),
    (42, '3', array[64, 65, 66]::smallint[], false),
    (43, '3.5', array[64, 65, 66]::smallint[], false),
    (44, '4', array[64, 65, 66]::smallint[], false),
    (45, '4.5', array[64, 65, 66]::smallint[], false),
    (46, '5', array[64, 65, 66]::smallint[], false),
    (47, '5.5', array[64, 65, 66]::smallint[], false),
    (48, '6', array[64, 65, 66]::smallint[], false),
    (49, '6.5', array[64, 65, 66]::smallint[], false),
    (50, '7', array[64, 65, 66]::smallint[], false),
    (51, '7.5', array[64, 65, 66]::smallint[], false),
    (52, '8', array[64, 65, 66]::smallint[], false),
    (53, '8.5', array[64, 65, 66]::smallint[], false),
    (54, '9', array[64, 65, 66]::smallint[], false),
    (55, '9.5', array[64, 65, 66]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'VISE' and l.name = 'IF Interchangeable Finger Round';

insert into grip_line (manufacturer, name, kind, colors) values ('VISE', 'Urethane Finger Slugs', 'FINGER_SLUG', array['Black']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (62, '31/32', array[62]::smallint[], false),
    (72, '1-1/8', array[72]::smallint[], false),
    (80, '1-1/4', array[80]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'VISE' and l.name = 'Urethane Finger Slugs';

insert into grip_line (manufacturer, name, kind, colors) values ('VISE', 'Pro V2 Vinyl Oval Thumb', 'THUMB_INSERT', array['White', 'Black']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (51, '51', array[72]::smallint[], false),
    (52, '13', array[72]::smallint[], false),
    (53, '53', array[72]::smallint[], false),
    (54, '27', array[72]::smallint[], false),
    (55, '55', array[72]::smallint[], false),
    (56, '7', array[72]::smallint[], false),
    (57, '57', array[72]::smallint[], false),
    (58, '29', array[72]::smallint[], false),
    (59, '59', array[72]::smallint[], false),
    (60, '15', array[72]::smallint[], false),
    (61, '61', array[72]::smallint[], false),
    (62, '31', array[72]::smallint[], false),
    (63, '63', array[72]::smallint[], false),
    (64, '1', array[80]::smallint[], false),
    (65, '1/6', array[80]::smallint[], false),
    (66, '1/3', array[80]::smallint[], false),
    (67, '3/6', array[80]::smallint[], false),
    (68, '1/1', array[80]::smallint[], false),
    (69, '5/6', array[80]::smallint[], false),
    (70, '3/3', array[80]::smallint[], false),
    (71, '7/6', array[80]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'VISE' and l.name = 'Pro V2 Vinyl Oval Thumb';

insert into grip_line (manufacturer, name, kind, colors) values ('VISE', 'Tapered Vinyl Oval Thumb', 'THUMB_INSERT', array['White', 'Black']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (51, '51', array[72]::smallint[], false),
    (52, '13', array[72]::smallint[], false),
    (53, '53', array[72]::smallint[], false),
    (54, '27', array[72]::smallint[], false),
    (55, '55', array[72]::smallint[], false),
    (56, '7', array[72]::smallint[], false),
    (57, '57', array[72]::smallint[], false),
    (58, '29', array[72]::smallint[], false),
    (59, '59', array[72]::smallint[], false),
    (60, '15', array[72]::smallint[], false),
    (61, '61', array[72]::smallint[], false),
    (62, '31', array[72]::smallint[], false),
    (63, '63', array[72]::smallint[], false),
    (64, '1', array[80]::smallint[], false),
    (65, '1/6', array[80]::smallint[], false),
    (66, '1/3', array[80]::smallint[], false),
    (67, '3/6', array[80]::smallint[], false),
    (68, '1/1', array[80]::smallint[], false),
    (69, '5/6', array[80]::smallint[], false),
    (70, '3/3', array[80]::smallint[], false),
    (71, '7/6', array[80]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'VISE' and l.name = 'Tapered Vinyl Oval Thumb';

insert into grip_line (manufacturer, name, kind, colors) values ('VISE', 'Tapered Vinyl Round Thumb', 'THUMB_INSERT', array['White', 'Black']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (51, '51', array[72]::smallint[], false),
    (52, '13', array[72]::smallint[], false),
    (53, '53', array[72]::smallint[], false),
    (54, '27', array[72]::smallint[], false),
    (55, '55', array[72]::smallint[], false),
    (56, '7', array[72]::smallint[], false),
    (57, '57', array[72]::smallint[], false),
    (58, '29', array[72]::smallint[], false),
    (59, '59', array[72]::smallint[], false),
    (60, '15', array[72]::smallint[], false),
    (61, '61', array[72]::smallint[], false),
    (62, '31', array[72]::smallint[], false),
    (63, '63', array[72]::smallint[], false),
    (64, '1', array[80]::smallint[], false),
    (65, '1/6', array[80]::smallint[], false),
    (66, '1/3', array[80]::smallint[], false),
    (67, '3/6', array[80]::smallint[], false),
    (68, '1/1', array[80]::smallint[], false),
    (69, '5/6', array[80]::smallint[], false),
    (70, '3/3', array[80]::smallint[], false),
    (71, '7/6', array[80]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'VISE' and l.name = 'Tapered Vinyl Round Thumb';

insert into grip_line (manufacturer, name, kind, colors) values ('VISE', 'Vinyl Thumb Slugs', 'THUMB_SLUG', array['Yellow', 'White', 'Black', 'Green', 'Orange', 'Blue', 'Purple', 'Pink', 'Red']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (72, '1-1/8', array[72]::smallint[], false),
    (80, '1-1/4', array[80]::smallint[], false),
    (88, '1-3/8', array[88]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'VISE' and l.name = 'Vinyl Thumb Slugs';

insert into grip_line (manufacturer, name, kind, colors) values ('VISE', 'Easy Urethane Thumb Slugs', 'THUMB_SLUG', array['Yellow', 'White', 'Black', 'Neon', 'Green', 'Orange', 'Blue', 'Purple', 'Pink', 'Red', 'Grape', 'Clear']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (72, '1-1/8', array[72]::smallint[], false),
    (80, '1-1/4', array[80]::smallint[], false),
    (88, '1-3/8', array[88]::smallint[], false),
    (96, '1-1/2', array[96]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'VISE' and l.name = 'Easy Urethane Thumb Slugs';

insert into grip_line (manufacturer, name, kind, colors) values ('VISE', 'Dual Easy Urethane Thumb Slugs', 'THUMB_SLUG', array['White/Black', 'Green/Orange', 'Yellow/Grape', 'Neon/Red', 'Pink/Blue']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (72, '1-1/8', array[72]::smallint[], false),
    (80, '1-1/4', array[80]::smallint[], false),
    (88, '1-3/8', array[88]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'VISE' and l.name = 'Dual Easy Urethane Thumb Slugs';

insert into grip_line (manufacturer, name, kind, colors) values ('VISE', 'IT Interchangeable Thumb', 'INTERCHANGEABLE_THUMB', array['Yellow', 'White', 'Black', 'Neon', 'Green', 'Orange', 'Blue', 'Purple', 'Pink', 'Red', 'Grape', 'Clear', 'Black XL']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (72, '1-1/8', array[76]::smallint[], true),
    (80, '1-1/4', array[84]::smallint[], true),
    (88, '1-3/8', array[92]::smallint[], true),
    (96, '1-1/2', array[100]::smallint[], true)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'VISE' and l.name = 'IT Interchangeable Thumb';

insert into grip_line (manufacturer, name, kind, colors) values ('TURBO', 'Quad', 'FINGER_INSERT', array['Black', 'White', 'Ice/Clear', 'Yellow', 'Red', 'Blue', 'Green', 'Orange', 'Purple', 'Pink']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (38, '1', array[62]::smallint[], false),
    (39, '1.5', array[62]::smallint[], false),
    (40, '2', array[62]::smallint[], false),
    (41, '2.5', array[62]::smallint[], false),
    (42, '3', array[62]::smallint[], false),
    (43, '3.5', array[62]::smallint[], false),
    (44, '4', array[62]::smallint[], false),
    (45, '4.5', array[62]::smallint[], false),
    (46, '5', array[62]::smallint[], false),
    (47, '5.5', array[62]::smallint[], false),
    (48, '6', array[62]::smallint[], false),
    (49, '6.5', array[62]::smallint[], false),
    (50, '7', array[62]::smallint[], false),
    (51, '7.5', array[62]::smallint[], false),
    (52, '8', array[62]::smallint[], false),
    (53, '8.5', array[66]::smallint[], false),
    (54, '9', array[66]::smallint[], false),
    (56, '10', array[66]::smallint[], false),
    (58, '11', array[66]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'TURBO' and l.name = 'Quad';

insert into grip_line (manufacturer, name, kind, colors) values ('TURBO', 'Classic', 'FINGER_INSERT', array['Black', 'White', 'Ice/Clear', 'Yellow', 'Red', 'Blue', 'Green', 'Orange', 'Purple', 'Pink']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (38, '1', array[62]::smallint[], false),
    (39, '1.5', array[62]::smallint[], false),
    (40, '2', array[62]::smallint[], false),
    (41, '2.5', array[62]::smallint[], false),
    (42, '3', array[62]::smallint[], false),
    (43, '3.5', array[62]::smallint[], false),
    (44, '4', array[62]::smallint[], false),
    (45, '4.5', array[62]::smallint[], false),
    (46, '5', array[62]::smallint[], false),
    (47, '5.5', array[62]::smallint[], false),
    (48, '6', array[62]::smallint[], false),
    (49, '6.5', array[62]::smallint[], false),
    (50, '7', array[62]::smallint[], false),
    (51, '7.5', array[62]::smallint[], false),
    (52, '8', array[62]::smallint[], false),
    (53, '8.5', array[66]::smallint[], false),
    (54, '9', array[66]::smallint[], false),
    (56, '10', array[66]::smallint[], false),
    (58, '11', array[66]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'TURBO' and l.name = 'Classic';

insert into grip_line (manufacturer, name, kind, colors) values ('TURBO', 'Classic Pro', 'FINGER_INSERT', array['Black', 'Blue']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (38, '1', array[62]::smallint[], false),
    (39, '1.5', array[62]::smallint[], false),
    (40, '2', array[62]::smallint[], false),
    (41, '2.5', array[62]::smallint[], false),
    (42, '3', array[62]::smallint[], false),
    (43, '3.5', array[62]::smallint[], false),
    (44, '4', array[62]::smallint[], false),
    (45, '4.5', array[62]::smallint[], false),
    (46, '5', array[62]::smallint[], false),
    (47, '5.5', array[62]::smallint[], false),
    (48, '6', array[62]::smallint[], false),
    (49, '6.5', array[62]::smallint[], false),
    (50, '7', array[62]::smallint[], false),
    (51, '7.5', array[62]::smallint[], false),
    (52, '8', array[62]::smallint[], false),
    (53, '8.5', array[66]::smallint[], false),
    (54, '9', array[66]::smallint[], false),
    (56, '10', array[66]::smallint[], false),
    (58, '11', array[66]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'TURBO' and l.name = 'Classic Pro';

insert into grip_line (manufacturer, name, kind, colors) values ('TURBO', 'Quad 2', 'FINGER_INSERT', array['Black', 'Ice/Clear']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (38, '1', array[62]::smallint[], false),
    (39, '1.5', array[62]::smallint[], false),
    (40, '2', array[62]::smallint[], false),
    (41, '2.5', array[62]::smallint[], false),
    (42, '3', array[62]::smallint[], false),
    (43, '3.5', array[62]::smallint[], false),
    (44, '4', array[62]::smallint[], false),
    (45, '4.5', array[62]::smallint[], false),
    (46, '5', array[62]::smallint[], false),
    (47, '5.5', array[62]::smallint[], false),
    (48, '6', array[62]::smallint[], false),
    (49, '6.5', array[62]::smallint[], false),
    (50, '7', array[62]::smallint[], false),
    (51, '7.5', array[62]::smallint[], false),
    (52, '8', array[62]::smallint[], false),
    (53, '8.5', array[66]::smallint[], false),
    (54, '9', array[66]::smallint[], false),
    (56, '10', array[66]::smallint[], false),
    (58, '11', array[66]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'TURBO' and l.name = 'Quad 2';

insert into grip_line (manufacturer, name, kind, colors) values ('TURBO', 'Power-SB', 'FINGER_INSERT', array['Black', 'Ice/Clear']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (38, '1', array[62]::smallint[], false),
    (39, '1.5', array[62]::smallint[], false),
    (40, '2', array[62]::smallint[], false),
    (41, '2.5', array[62]::smallint[], false),
    (42, '3', array[62]::smallint[], false),
    (43, '3.5', array[62]::smallint[], false),
    (44, '4', array[62]::smallint[], false),
    (45, '4.5', array[62]::smallint[], false),
    (46, '5', array[62]::smallint[], false),
    (47, '5.5', array[62]::smallint[], false),
    (48, '6', array[62]::smallint[], false),
    (49, '6.5', array[62]::smallint[], false),
    (50, '7', array[62]::smallint[], false),
    (51, '7.5', array[62]::smallint[], false),
    (52, '8', array[62]::smallint[], false),
    (53, '8.5', array[66]::smallint[], false),
    (54, '9', array[66]::smallint[], false),
    (56, '10', array[66]::smallint[], false),
    (58, '11', array[66]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'TURBO' and l.name = 'Power-SB';

insert into grip_line (manufacturer, name, kind, colors) values ('TURBO', 'Ms. Quad', 'FINGER_INSERT', array['Black', 'White', 'Ice/Clear', 'Yellow', 'Pink']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (34, '-1', array[56]::smallint[], false),
    (35, '-0.5', array[56]::smallint[], false),
    (36, '0', array[56]::smallint[], false),
    (37, '0.5', array[56]::smallint[], false),
    (38, '1', array[56]::smallint[], false),
    (39, '1.5', array[56]::smallint[], false),
    (40, '2', array[56]::smallint[], false),
    (41, '2.5', array[56]::smallint[], false),
    (42, '3', array[56]::smallint[], false),
    (43, '3.5', array[56]::smallint[], false),
    (44, '4', array[56]::smallint[], false),
    (45, '4.5', array[56]::smallint[], false),
    (46, '5', array[56]::smallint[], false),
    (47, '5.5', array[56]::smallint[], false),
    (48, '6', array[56]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'TURBO' and l.name = 'Ms. Quad';

insert into grip_line (manufacturer, name, kind, colors) values ('TURBO', 'Urethane Finger Solids', 'FINGER_SLUG', array['Black']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (62, '31/32', array[62]::smallint[], false),
    (72, '1-1/8', array[72]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'TURBO' and l.name = 'Urethane Finger Solids';

insert into grip_line (manufacturer, name, kind, colors) values ('TURBO', 'Xcel Thumb Round', 'THUMB_INSERT', array['Black']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (51, '51/64', array[72]::smallint[], false),
    (52, '13/16', array[72]::smallint[], false),
    (53, '53/64', array[72]::smallint[], false),
    (54, '27/32', array[72]::smallint[], false),
    (55, '55/64', array[72]::smallint[], false),
    (56, '7/8', array[72]::smallint[], false),
    (57, '57/64', array[72]::smallint[], false),
    (58, '29/32', array[72]::smallint[], false),
    (59, '59/64', array[72]::smallint[], false),
    (60, '15/16', array[72]::smallint[], false),
    (61, '61/64', array[72]::smallint[], false),
    (62, '31/32', array[80]::smallint[], false),
    (63, '63/64', array[80]::smallint[], false),
    (64, '1', array[80]::smallint[], false),
    (65, '1-1/64', array[80]::smallint[], false),
    (66, '1-1/32', array[80]::smallint[], false),
    (67, '1-3/64', array[80]::smallint[], false),
    (68, '1-1/16', array[80]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'TURBO' and l.name = 'Xcel Thumb Round';

insert into grip_line (manufacturer, name, kind, colors) values ('TURBO', 'Xcel Thumb Oval', 'THUMB_INSERT', array['Black']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (51, '51/64', array[72]::smallint[], false),
    (52, '13/16', array[72]::smallint[], false),
    (53, '53/64', array[72]::smallint[], false),
    (54, '27/32', array[72]::smallint[], false),
    (55, '55/64', array[72]::smallint[], false),
    (56, '7/8', array[72]::smallint[], false),
    (57, '57/64', array[72]::smallint[], false),
    (58, '29/32', array[72]::smallint[], false),
    (59, '59/64', array[72]::smallint[], false),
    (60, '15/16', array[72]::smallint[], false),
    (61, '61/64', array[72]::smallint[], false),
    (62, '31/32', array[80]::smallint[], false),
    (63, '63/64', array[80]::smallint[], false),
    (64, '1', array[80]::smallint[], false),
    (65, '1-1/64', array[80]::smallint[], false),
    (66, '1-1/32', array[80]::smallint[], false),
    (67, '1-3/64', array[80]::smallint[], false),
    (68, '1-1/16', array[80]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'TURBO' and l.name = 'Xcel Thumb Oval';

insert into grip_line (manufacturer, name, kind, colors) values ('TURBO', 'Urethane Thumb Solids', 'THUMB_SLUG', array['Black/White', 'Orange/Yellow', 'Blue/Purple', 'Green/Red', 'Pink/White', 'White', 'Black']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (72, '1-1/8', array[72]::smallint[], false),
    (80, '1-1/4', array[80]::smallint[], false),
    (88, '1-3/8', array[88]::smallint[], false),
    (96, '1-1/2', array[96]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'TURBO' and l.name = 'Urethane Thumb Solids';

insert into grip_line (manufacturer, name, kind, colors) values ('TURBO', 'Switch Grip', 'INTERCHANGEABLE_THUMB', array['Black', 'Orange', 'Yellow', 'Green', 'Blue', 'Red', 'Pink', 'Purple']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (96, 'Outer sleeve', array[96]::smallint[], true)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'TURBO' and l.name = 'Switch Grip';

insert into grip_line (manufacturer, name, kind, colors) values ('TURBO', 'Switch Grip NX', 'INTERCHANGEABLE_THUMB', array['Black', 'Red']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (96, 'Outer sleeve', array[96]::smallint[], true)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'TURBO' and l.name = 'Switch Grip NX';

insert into grip_line (manufacturer, name, kind, colors) values ('JOPO', 'Power Flat / Oval', 'FINGER_INSERT', array['Black', 'Blue', 'Green', 'Orange', 'Pink', 'Purple', 'Red', 'White', 'Yellow']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (38, '19/32', array[62]::smallint[], false),
    (39, '39/64', array[62]::smallint[], false),
    (40, '5/8', array[62]::smallint[], false),
    (41, '41/64', array[62]::smallint[], false),
    (42, '21/32', array[62]::smallint[], false),
    (43, '43/64', array[62]::smallint[], false),
    (44, '11/16', array[62]::smallint[], false),
    (45, '45/64', array[62]::smallint[], false),
    (46, '23/32', array[62]::smallint[], false),
    (47, '47/64', array[62]::smallint[], false),
    (48, '3/4', array[62]::smallint[], false),
    (49, '49/64', array[62]::smallint[], false),
    (50, '25/32', array[62]::smallint[], false),
    (51, '51/64', array[62]::smallint[], false),
    (52, '13/16', array[62]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'JOPO' and l.name = 'Power Flat / Oval';

insert into grip_line (manufacturer, name, kind, colors) values ('JOPO', 'Oval / Oval Dots', 'FINGER_INSERT', array['Black', 'Blue', 'Green', 'Orange', 'Pink', 'Purple', 'Red', 'White', 'Yellow']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (38, '19/32', array[62]::smallint[], false),
    (39, '39/64', array[62]::smallint[], false),
    (40, '5/8', array[62]::smallint[], false),
    (41, '41/64', array[62]::smallint[], false),
    (42, '21/32', array[62]::smallint[], false),
    (43, '43/64', array[62]::smallint[], false),
    (44, '11/16', array[62]::smallint[], false),
    (45, '45/64', array[62]::smallint[], false),
    (46, '23/32', array[62]::smallint[], false),
    (47, '47/64', array[62]::smallint[], false),
    (48, '3/4', array[62]::smallint[], false),
    (49, '49/64', array[62]::smallint[], false),
    (50, '25/32', array[62]::smallint[], false),
    (51, '51/64', array[62]::smallint[], false),
    (52, '13/16', array[62]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'JOPO' and l.name = 'Oval / Oval Dots';

insert into grip_line (manufacturer, name, kind, colors) values ('JOPO', 'Thumb Slugs', 'THUMB_SLUG', array['Black', 'Blue', 'Green', 'Orange', 'Pink', 'Purple', 'Red', 'White', 'Yellow']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (72, '1-1/8', array[72]::smallint[], false),
    (80, '1-1/4', array[80]::smallint[], false),
    (88, '1-3/8', array[88]::smallint[], false),
    (96, '1-1/2', array[96]::smallint[], false)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'JOPO' and l.name = 'Thumb Slugs';

insert into grip_line (manufacturer, name, kind, colors) values ('JOPO', 'Twist', 'INTERCHANGEABLE_THUMB', array['Black', 'Blue', 'Green', 'Orange', 'Pink', 'Purple', 'Red', 'White', 'Yellow', 'Twisted']::text[]);

insert into grip_size (line_id, size64, label, od64_choices, collar)
select l.id, v.size64, v.label, v.od64_choices, v.collar
from grip_line l, (values
    (96, 'Outer', array[96]::smallint[], true)
) as v(size64, label, od64_choices, collar)
where l.manufacturer = 'JOPO' and l.name = 'Twist';


-- migrate:down

drop table location_grip_stock;
drop table grip_size;
drop table grip_line;
