// amplify_outputs.json is generated by `npx ampx sandbox` (local) or the
// Amplify pipeline deploy and is not committed. import.meta.glob tolerates the
// file being absent, so the build works without it.
const outputModules = import.meta.glob<{ default: Record<string, unknown> }>(
    '../../amplify_outputs.json',
    { eager: true }
)

/** The Amplify outputs, or undefined when the file is absent. */
export const amplifyOutputs = Object.values(outputModules)[0]?.default

/** Cognito sign-in is configured. Without it the app runs on mock data. */
export const authEnabled = Boolean(amplifyOutputs?.auth)

/** Base URL of the REST API (amplify/api), when deployed. */
export const apiUrl: string | undefined =
    (amplifyOutputs?.custom as { api?: { url?: string } } | undefined)?.api?.url?.replace(/\/$/, '')

/** Hooks read and write through the API only when signed in and the API exists. */
export const apiEnabled = authEnabled && Boolean(apiUrl)
