/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AppUser {
  active: Generated<boolean>;
  cognito_sub: string | null;
  company_id: string;
  company_role: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  first_name: string;
  hire_date: Timestamp | null;
  hourly_rate: Numeric | null;
  id: Generated<string>;
  /**
   * When the last invitation email was sent. Null for users created by the seed script.
   */
  invited_at: Timestamp | null;
  last_name: string;
  phone: string | null;
  specialties: Generated<string[]>;
  updated_at: Generated<Timestamp>;
}

export interface Ball {
  brand_id: string | null;
  catalog_ball_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  serial_number: string | null;
  weight_lbs: number;
}

export interface BallOwnership {
  company_ball_id: string;
  company_id: string;
  created_at: Generated<Timestamp>;
  customer_id: string;
  from_date: Timestamp;
  id: Generated<string>;
  to_date: Timestamp | null;
}

export interface CatalogBall {
  brand_id: string;
  brand_name: string;
  color: string | null;
  content_changed_at: Timestamp;
  data: Json;
  id: string;
  name: string;
  removed_at: Timestamp | null;
  status: string;
  synced_at: Generated<Timestamp>;
}

export interface CatalogSyncState {
  cursor: string | null;
  id: Generated<number>;
  last_run_at: Timestamp | null;
}

export interface Company {
  billing_address: Json | null;
  billing_cycle: string | null;
  billing_email: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  plan_code: string;
  settings: Generated<Json>;
  updated_at: Generated<Timestamp>;
}

export interface CompanyBall {
  ball_id: string;
  company_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  model_id: string | null;
  notes: string | null;
  pin_distance: Numeric | null;
  purchase_date: Timestamp | null;
  purchase_price: Numeric | null;
  specs: Generated<Json>;
  status: Generated<string>;
  top_weight: Numeric | null;
  updated_at: Generated<Timestamp>;
}

export interface CompanyBallModel {
  brand_id: string | null;
  brand_name: string;
  color: string | null;
  company_id: string;
  core: string | null;
  coverstock: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
}

export interface Customer {
  axis_rotation_degrees: Numeric | null;
  axis_tilt_degrees: Numeric | null;
  company_id: string;
  created_at: Generated<Timestamp>;
  dominant_hand: string;
  email: string | null;
  first_name: string;
  home_location_id: string | null;
  id: Generated<string>;
  last_name: string;
  notes: string | null;
  pap_over_32: number | null;
  pap_up_32: number | null;
  phone: string | null;
  preferred_grip_style: string;
  rev_rate_rpm: number | null;
  speed_mph: Numeric | null;
  updated_at: Generated<Timestamp>;
  uses_thumb: Generated<boolean>;
}

export interface CustomerAttachment {
  company_id: string;
  content_type: string;
  created_at: Generated<Timestamp>;
  created_by_user_id: string;
  customer_id: string;
  file_name: string;
  id: Generated<string>;
  kind: Generated<string>;
  label: string | null;
  rotation: Generated<number>;
  size_bytes: Int8;
  storage_key: string;
  updated_at: Generated<Timestamp>;
  uploaded: Generated<boolean>;
}

export interface DrillSheet {
  archived_at: Timestamp | null;
  based_on_template_id: string | null;
  company_id: string;
  created_at: Generated<Timestamp>;
  current_revision_id: string | null;
  customer_id: string | null;
  grip_style: string;
  id: Generated<string>;
  is_template: Generated<boolean>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface DrillSheetRevision {
  approved_at: Timestamp | null;
  approved_by_user_id: string | null;
  /**
   * Bridge in 32nds of an inch, edge-to-edge: the material between the middle and ring finger holes.
   */
  bridge_32: number | null;
  company_id: string;
  created_at: Generated<Timestamp>;
  created_by_user_id: string;
  drill_sheet_id: string;
  id: Generated<string>;
  location_id: string | null;
  middle_size_64: number | null;
  revision_notes: string | null;
  ring_size_64: number | null;
  /**
   * Full drill sheet spec (docs/data-model.md, spec_schema_version). Pitch values are inches only.
   */
  spec: Json;
  spec_schema_version: number;
  thumb_size_64: number | null;
  /**
   * Center-to-center span in 32nds of an inch (CAD/CNC spec).
   */
  thumb_to_middle_ctc_32: number | null;
  /**
   * Cut-to-cut span in 32nds of an inch: drilled hole edge to drilled hole edge, before hardware.
   */
  thumb_to_middle_cut_32: number | null;
  /**
   * Fit span in 32nds of an inch: center of the finger hole to the cut edge of the thumb.
   */
  thumb_to_middle_fit_32: number | null;
  /**
   * Full span in 32nds of an inch: gripping edge to gripping edge.
   */
  thumb_to_middle_full_32: number | null;
  /**
   * Outer-to-cut span in 32nds of an inch: outer edge of the thumb hardware (inner not installed) to the finger's drilled hole edge.
   */
  thumb_to_middle_outer_32: number | null;
  thumb_to_ring_ctc_32: number | null;
  thumb_to_ring_cut_32: number | null;
  thumb_to_ring_fit_32: number | null;
  thumb_to_ring_full_32: number | null;
  thumb_to_ring_outer_32: number | null;
  updated_at: Generated<Timestamp>;
  /**
   * Who last saved this revision (a draft is edited in place).
   */
  updated_by_user_id: string | null;
  version: number;
}

export interface Equipment {
  company_id: string;
  created_at: Generated<Timestamp>;
  created_by_user_id: string | null;
  details: Generated<Json>;
  id: Generated<string>;
  kind: string;
  location_id: string;
  manufacturer: string | null;
  model: string | null;
  name: string;
  notes: string | null;
  purchased_on: Timestamp | null;
  serial_number: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  volume: Generated<string>;
}

export interface GripLine {
  active: Generated<boolean>;
  colors: Generated<string[]>;
  id: Generated<string>;
  install_styles: Generated<string[]>;
  kind: string;
  manufacturer: string;
  name: string;
}

export interface GripSize {
  collar: Generated<boolean>;
  id: Generated<string>;
  label: string;
  line_id: string;
  od64_choices: number[];
  size64: number;
}

export interface LayoutTemplate {
  archived_at: Timestamp | null;
  company_id: string;
  created_at: Generated<Timestamp>;
  created_by_user_id: string;
  customer_id: string | null;
  id: Generated<string>;
  layout: Json;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Lead {
  balls_per_month: string;
  city: string | null;
  company_id: string | null;
  country: Generated<string>;
  created_at: Generated<Timestamp>;
  current_software: string | null;
  current_tools: string | null;
  drill_press: string | null;
  driller_count: string | null;
  email: string;
  first_name: string;
  grips: Generated<string[]>;
  heard_from: string | null;
  id: Generated<string>;
  last_name: string;
  location_count: string;
  marketing_consent: Generated<boolean>;
  pain_point: string | null;
  phone: string | null;
  region: string | null;
  role: string;
  shop_name: string;
  shop_type: string | null;
  source: Generated<Json>;
  status: Generated<string>;
  timeline: string | null;
  updated_at: Generated<Timestamp>;
}

export interface LeadNote {
  author_name: string;
  body: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  lead_id: string;
}

export interface Location {
  active: Generated<boolean>;
  address: Json | null;
  company_id: string;
  created_at: Generated<Timestamp>;
  email: string | null;
  hours: Json | null;
  id: Generated<string>;
  name: string;
  phone: string | null;
  settings_overrides: Generated<Json>;
  timezone: string;
  updated_at: Generated<Timestamp>;
  website: string | null;
}

export interface LocationGripStock {
  company_id: string;
  created_at: Generated<Timestamp>;
  grip_size_id: string;
  location_id: string;
}

export interface LocationMembership {
  company_id: string;
  created_at: Generated<Timestamp>;
  location_id: string;
  role: string;
  user_id: string;
}

export interface MaintenanceLog {
  checklist: Generated<Json>;
  company_id: string;
  done_at: Generated<Timestamp>;
  done_by_user_id: string | null;
  equipment_id: string;
  id: Generated<string>;
  issue_type: string | null;
  kind: string;
  notes: string | null;
  task_id: string | null;
  title: string;
}

export interface MaintenanceTask {
  active: Generated<boolean>;
  checklist: Generated<Json>;
  company_id: string;
  created_at: Generated<Timestamp>;
  equipment_id: string;
  guidance: string | null;
  id: Generated<string>;
  interval_balls: number | null;
  interval_days: number | null;
  last_done_at: Timestamp | null;
  next_due_on: Timestamp | null;
  template_code: string | null;
  title: string;
  updated_at: Generated<Timestamp>;
  video_url: string | null;
}

export interface PaperImport {
  attachment_id: string | null;
  company_id: string;
  content_type: string;
  /**
   * The transcription as the reviewer corrected it; differences from reading become hints for this company's later imports.
   */
  corrected_reading: Json | null;
  created_at: Generated<Timestamp>;
  created_by_user_id: string;
  customer_id: string | null;
  drill_sheet_id: string | null;
  error: string | null;
  file_name: string;
  id: Generated<string>;
  imported_at: Timestamp | null;
  imported_by_user_id: string | null;
  imported_spec: Json | null;
  location_id: string | null;
  read_at: Timestamp | null;
  reader_model: string | null;
  reading: Json | null;
  size_bytes: Int8;
  span_type: string | null;
  status: Generated<string>;
  storage_key: string;
  template: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Plan {
  code: string;
  included_locations: number;
  name: string;
}

export interface WorkOrder {
  based_on_layout_template_id: string | null;
  company_ball_id: string;
  company_id: string;
  created_at: Generated<Timestamp>;
  customer_id: string;
  customer_satisfaction: number | null;
  deviations_from_spec: string | null;
  drill_sheet_revision_id: string | null;
  ended_at: Timestamp | null;
  id: Generated<string>;
  labor_cost: Numeric | null;
  labor_hours: Numeric | null;
  layout: Json | null;
  location_id: string;
  materials_cost: Numeric | null;
  notes: string | null;
  performed_by_user_id: string | null;
  quality_check: boolean | null;
  quality_notes: string | null;
  started_at: Timestamp | null;
  total_cost: Numeric | null;
  updated_at: Generated<Timestamp>;
  warranty_days: number | null;
  work_date: Timestamp;
  work_type: string;
}

export interface WorkOrderPhoto {
  company_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  s3_key: string;
  work_order_id: string;
}

export interface DB {
  app_user: AppUser;
  ball: Ball;
  ball_ownership: BallOwnership;
  catalog_ball: CatalogBall;
  catalog_sync_state: CatalogSyncState;
  company: Company;
  company_ball: CompanyBall;
  company_ball_model: CompanyBallModel;
  customer: Customer;
  customer_attachment: CustomerAttachment;
  drill_sheet: DrillSheet;
  drill_sheet_revision: DrillSheetRevision;
  equipment: Equipment;
  grip_line: GripLine;
  grip_size: GripSize;
  layout_template: LayoutTemplate;
  lead: Lead;
  lead_note: LeadNote;
  location: Location;
  location_grip_stock: LocationGripStock;
  location_membership: LocationMembership;
  maintenance_log: MaintenanceLog;
  maintenance_task: MaintenanceTask;
  paper_import: PaperImport;
  plan: Plan;
  work_order: WorkOrder;
  work_order_photo: WorkOrderPhoto;
}
