import React from 'react'
import ReactDOM from 'react-dom/client'
import { Amplify } from 'aws-amplify'
import App from './App.tsx'
import { AuthWrapper } from './components/auth/AuthWrapper'
import './index.css'

// amplify_outputs.json is generated by `npx ampx sandbox` (local) or the
// Amplify pipeline deploy and is not committed. import.meta.glob tolerates the
// file being absent, so the build works without it.
const outputModules = import.meta.glob<{ default: Record<string, unknown> }>(
    '../amplify_outputs.json',
    { eager: true }
)
const outputs = Object.values(outputModules)[0]?.default
const authEnabled = Boolean(outputs?.auth)

if (authEnabled) {
    Amplify.configure(outputs as Parameters<typeof Amplify.configure>[0])
} else {
    // Local development on mock data. Once hooks read real data, production
    // must refuse to run without auth instead of falling back to this.
    console.warn('Auth is not configured (no auth section in amplify_outputs.json). Running without sign-in on mock data.')
}

ReactDOM.createRoot(document.getElementById('root')!).render(
    <React.StrictMode>
        {authEnabled
            ? <AuthWrapper>{(user) => <App user={user} />}</AuthWrapper>
            : <App />}
    </React.StrictMode>,
)
