import type { GripLineDto } from '../../shared/api/grips'
import type { GripsApi } from '../services/gripsService'
import catalog from './mockGripCatalog.json'

// The grip catalog without the API: the same rows the migration seeds
// (generated by db/seed/grip_catalog.py --json), and stock kept in memory.

const stockByLocation = new Map<string, string[]>()
const pause = () => new Promise(resolve => setTimeout(resolve, 200))

export const mockGripsApi: GripsApi = {
    async catalog() {
        await pause()
        return catalog as GripLineDto[]
    },
    async stock(locationId) {
        await pause()
        return { gripSizeIds: stockByLocation.get(locationId) ?? [] }
    },
    async setStock(locationId, stock) {
        await pause()
        stockByLocation.set(locationId, [...new Set(stock.gripSizeIds)])
        return { gripSizeIds: stockByLocation.get(locationId)! }
    }
}
